import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Klasifikasi Kacamata dan Helm Menggunakan Deep Learning (CNN)\n",
    "Notebook ini mengimplementasikan Solusi A (Convolutional Neural Network) menggunakan TensorFlow/Keras.\n",
    "\n",
    "**Kelebihan CNN:**\n",
    "- Secara otomatis mengenali pola spasial (bentuk, garis, tekstur) dari objek 2D.\n",
    "- Tidak memerlukan teknik preprocessing destruktif (seperti OTSU threshold yang memotong bentuk asli).\n",
    "- Lebih kebal (robust) terhadap *noise* di background.\n",
    "\n",
    "**Catatan Penting Mengenai Dataset Anda:**\n",
    "Data latih (*train*) Anda berisi gambar kacamata biasa, sementara data uji (*test*) Anda hampir seluruhnya adalah kacamata pelindung proyek (*safety goggles*). Ini adalah kasus **Domain Shift**. CNN mungkin bisa mengenali *safety goggles* lebih baik karena bisa mencari kesamaan struktur umum (misal lensa dan frame), tetapi jika performa masih dirasa kurang sempurna, tambahkan gambar *safety goggles* ke dalam data `train` Anda!"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import os\n",
    "import glob\n",
    "from tqdm.notebook import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "IMG_SIZE = (64, 64)\n",
    "\n",
    "def load_data(data_dir):\n",
    "    categories = {\"helm\": 0, \"kacamata\": 1}\n",
    "    X, y = [], []\n",
    "    for label_name, label_id in categories.items():\n",
    "        folder = os.path.join(data_dir, label_name)\n",
    "        files = glob.glob(os.path.join(folder, \"*.*\"))\n",
    "        print(f\"Memproses '{label_name}': {len(files)} gambar ditemukan...\")\n",
    "        \n",
    "        for img_path in tqdm(files, desc=f\"Loading {label_name}\"):\n",
    "            img = cv2.imread(img_path)\n",
    "            if img is not None:\n",
    "                img_resized = cv2.resize(img, IMG_SIZE)\n",
    "                # Convert BGR ke RGB agar warna sesuai saat divisualisasi\n",
    "                img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)\n",
    "                X.append(img_rgb)\n",
    "                y.append(label_id)\n",
    "    return np.array(X), np.array(y)\n",
    "\n",
    "print(\"Memuat Data Train...\")\n",
    "X_train, y_train = load_data(\"dataset/train\")\n",
    "\n",
    "# Normalisasi pixel menjadi rentang 0 sampai 1 untuk membantu Neural Network belajar\n",
    "X_train = X_train.astype('float32') / 255.0\n",
    "\n",
    "print(f\"\\nDimensi X_train: {X_train.shape} (Jumlah Data, Height, Width, Channels)\")\n",
    "print(f\"Dimensi y_train: {y_train.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras import layers, models\n",
    "\n",
    "# Membangun Arsitektur CNN\n",
    "model = models.Sequential([\n",
    "    # Layer Konvolusi Pertama\n",
    "    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE[0], IMG_SIZE[1], 3)),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    \n",
    "    # Layer Konvolusi Kedua\n",
    "    layers.Conv2D(64, (3, 3), activation='relu'),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    \n",
    "    # Layer Konvolusi Ketiga\n",
    "    layers.Conv2D(128, (3, 3), activation='relu'),\n",
    "    layers.MaxPooling2D((2, 2)),\n",
    "    \n",
    "    # Meratakan matriks untuk dimasukkan ke Dense Layer (Fully Connected)\n",
    "    layers.Flatten(),\n",
    "    layers.Dense(128, activation='relu'),\n",
    "    \n",
    "    # Dropout digunakan untuk mematikan neuron acak agar tidak overfitting\n",
    "    layers.Dropout(0.5),\n",
    "    \n",
    "    # Output layer menggunakan Sigmoid karena ini Binary Classification (0 atau 1)\n",
    "    layers.Dense(1, activation='sigmoid')\n",
    "])\n",
    "\n",
    "model.compile(optimizer='adam',\n",
    "              loss='binary_crossentropy',\n",
    "              metrics=['accuracy'])\n",
    "\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.utils.class_weight import compute_class_weight\n",
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "# Split 20% data train untuk validasi\n",
    "X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42, stratify=y_train)\n",
    "\n",
    "# Menghitung class weights otomatis karena data tidak seimbang (Helm lebih banyak)\n",
    "classes = np.unique(y_train)\n",
    "weights = compute_class_weight(class_weight='balanced', classes=classes, y=y_train)\n",
    "class_weights = dict(zip(classes, weights))\n",
    "print(\"Class weights yang diterapkan:\", class_weights)\n",
    "\n",
    "print(\"\\nMemulai Training CNN...\")\n",
    "history = model.fit(\n",
    "    X_tr, y_tr,\n",
    "    epochs=15,             # Silakan naikkan epochs jika akurasi dirasa belum stabil\n",
    "    batch_size=32,\n",
    "    validation_data=(X_val, y_val),\n",
    "    class_weight=class_weights\n",
    ")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(12, 4))\n",
    "plt.subplot(1, 2, 1)\n",
    "plt.plot(history.history['accuracy'], label='Train Accuracy')\n",
    "plt.plot(history.history['val_accuracy'], label='Validation Accuracy')\n",
    "plt.legend()\n",
    "plt.title('Model Accuracy')\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "plt.plot(history.history['loss'], label='Train Loss')\n",
    "plt.plot(history.history['val_loss'], label='Validation Loss')\n",
    "plt.legend()\n",
    "plt.title('Model Loss')\n",
    "\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay\n",
    "\n",
    "print(\"Memuat Data Test...\")\n",
    "X_test, y_true_numeric = load_data(\"dataset/test\")\n",
    "X_test = X_test.astype('float32') / 255.0\n",
    "\n",
    "print(\"\\nEvaluasi Data Test...\")\n",
    "predictions = model.predict(X_test)\n",
    "\n",
    "# Ubah probabilitas ke class ID (threshold 0.5)\n",
    "y_pred_numeric = (predictions > 0.5).astype(int).flatten()\n",
    "\n",
    "y_true = [\"Helm\" if y == 0 else \"Kacamata\" for y in y_true_numeric]\n",
    "y_pred = [\"Helm\" if y == 0 else \"Kacamata\" for y in y_pred_numeric]\n",
    "\n",
    "labels = [\"Helm\", \"Kacamata\"]\n",
    "cm = confusion_matrix(y_true, y_pred, labels=labels)\n",
    "\n",
    "disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)\n",
    "disp.plot(cmap=\"Blues\")\n",
    "plt.title(\"Confusion Matrix - CNN\")\n",
    "plt.show()\n",
    "\n",
    "print(\"\\n--- CLASSIFICATION REPORT ---\")\n",
    "print(classification_report(y_true, y_pred, labels=labels, zero_division=0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def classify_demo_cnn(image_path, cnn_model):\n",
    "    img = cv2.imread(image_path)\n",
    "    if img is None:\n",
    "        return \"Error\"\n",
    "    \n",
    "    img_resized = cv2.resize(img, IMG_SIZE)\n",
    "    img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)\n",
    "    \n",
    "    # Preprocessing sama seperti saat training\n",
    "    input_tensor = np.expand_dims(img_rgb.astype('float32') / 255.0, axis=0)\n",
    "    \n",
    "    # Prediksi (Output berupa probabilitas kacamata)\n",
    "    prob = cnn_model.predict(input_tensor)[0][0]\n",
    "    pred_id = 1 if prob > 0.5 else 0\n",
    "    predicted_label = \"Kacamata\" if pred_id == 1 else \"Helm\"\n",
    "    \n",
    "    plt.figure(figsize=(4, 4))\n",
    "    plt.imshow(img_rgb)\n",
    "    plt.title(f\"CNN: {predicted_label} (Prob Kacamata: {prob:.2f})\")\n",
    "    plt.axis(\"off\")\n",
    "    plt.show()\n",
    "    \n",
    "    return predicted_label\n",
    "\n",
    "print(\"=== DEMO KLASIFIKASI CNN ===\")\n",
    "helm_samples = glob.glob(\"dataset/test/helm/*.*\")\n",
    "if helm_samples:\n",
    "    classify_demo_cnn(helm_samples[0], model)\n",
    "\n",
    "kaca_samples = glob.glob(\"dataset/test/kacamata/*.*\")\n",
    "if kaca_samples:\n",
    "    classify_demo_cnn(kaca_samples[0], model)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("new_cnn.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook new_cnn.ipynb berhasil dibuat!")
