import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Klasifikasi Kacamata dan Helm Menggunakan Deep Learning (PyTorch CNN)\n",
    "Karena instalasi TensorFlow Anda mengalami error (sering terjadi di Windows karena kendala prosesor/DLL), *notebook* ini dibuat menggunakan **PyTorch** sebagai alternatif yang jauh lebih stabil dan ringan.\n",
    "\n",
    "Model ini menggunakan Convolutional Neural Network (CNN) untuk mengekstraksi fitur visual secara otomatis dari gambar asli."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import os\n",
    "import glob\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import TensorDataset, DataLoader, WeightedRandomSampler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from tqdm.notebook import tqdm\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "IMG_SIZE = (64, 64)\n",
    "\n",
    "# Set device ke CPU atau GPU (jika tersedia)\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Menggunakan device: {device}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_data(data_dir):\n",
    "    categories = {\"helm\": 0, \"kacamata\": 1}\n",
    "    X, y = [], []\n",
    "    for label_name, label_id in categories.items():\n",
    "        folder = os.path.join(data_dir, label_name)\n",
    "        files = glob.glob(os.path.join(folder, \"*.*\"))\n",
    "        print(f\"Memproses '{label_name}': {len(files)} gambar ditemukan...\")\n",
    "        \n",
    "        for img_path in tqdm(files, desc=f\"Loading {label_name}\"):\n",
    "            img = cv2.imread(img_path)\n",
    "            if img is not None:\n",
    "                img_resized = cv2.resize(img, IMG_SIZE)\n",
    "                img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)\n",
    "                # PyTorch menggunakan format channel-first (Channels, Height, Width)\n",
    "                img_tensor = np.transpose(img_rgb, (2, 0, 1))\n",
    "                X.append(img_tensor)\n",
    "                y.append(label_id)\n",
    "    return np.array(X, dtype=np.float32) / 255.0, np.array(y, dtype=np.int64)\n",
    "\n",
    "print(\"Memuat Data Train...\")\n",
    "X_train, y_train = load_data(\"dataset/train\")\n",
    "print(f\"\\nDimensi X_train: {X_train.shape}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Split Train & Validation\n",
    "X_tr, X_val, y_tr, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42, stratify=y_train)\n",
    "\n",
    "# Menangani Ketidakseimbangan Data (Class Weights)\n",
    "class_sample_count = np.array([len(np.where(y_tr == t)[0]) for t in np.unique(y_tr)])\n",
    "weight = 1. / class_sample_count\n",
    "samples_weight = np.array([weight[t] for t in y_tr])\n",
    "samples_weight = torch.from_numpy(samples_weight).double()\n",
    "sampler = WeightedRandomSampler(samples_weight, len(samples_weight))\n",
    "\n",
    "# Buat DataLoader\n",
    "train_dataset = TensorDataset(torch.tensor(X_tr), torch.tensor(y_tr))\n",
    "train_loader = DataLoader(train_dataset, batch_size=32, sampler=sampler)\n",
    "\n",
    "val_dataset = TensorDataset(torch.tensor(X_val), torch.tensor(y_val))\n",
    "val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class CNNClassifier(nn.Module):\n",
    "    def __init__(self):\n",
    "        super(CNNClassifier, self).__init__()\n",
    "        self.features = nn.Sequential(\n",
    "            nn.Conv2d(3, 32, kernel_size=3, padding=1),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(2, 2),\n",
    "            \n",
    "            nn.Conv2d(32, 64, kernel_size=3, padding=1),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(2, 2),\n",
    "            \n",
    "            nn.Conv2d(64, 128, kernel_size=3, padding=1),\n",
    "            nn.ReLU(),\n",
    "            nn.MaxPool2d(2, 2)\n",
    "        )\n",
    "        self.classifier = nn.Sequential(\n",
    "            nn.Flatten(),\n",
    "            nn.Linear(128 * 8 * 8, 128),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(0.5),\n",
    "            nn.Linear(128, 1) # Output tunggal untuk binary classification\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.features(x)\n",
    "        x = self.classifier(x)\n",
    "        return x\n",
    "\n",
    "model = CNNClassifier().to(device)\n",
    "criterion = nn.BCEWithLogitsLoss() # Termasuk Sigmoid otomatis\n",
    "optimizer = optim.Adam(model.parameters(), lr=0.001)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "epochs = 15\n",
    "train_losses, val_losses = [], []\n",
    "train_accs, val_accs = [], []\n",
    "\n",
    "print(\"Memulai Training CNN...\")\n",
    "for epoch in range(epochs):\n",
    "    model.train()\n",
    "    running_loss, correct, total = 0.0, 0, 0\n",
    "    for inputs, labels in train_loader:\n",
    "        inputs, labels = inputs.to(device), labels.float().to(device)\n",
    "        \n",
    "        optimizer.zero_grad()\n",
    "        outputs = model(inputs).squeeze()\n",
    "        loss = criterion(outputs, labels)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "        running_loss += loss.item() * inputs.size(0)\n",
    "        preds = (torch.sigmoid(outputs) > 0.5).float()\n",
    "        correct += (preds == labels).sum().item()\n",
    "        total += labels.size(0)\n",
    "        \n",
    "    train_losses.append(running_loss / total)\n",
    "    train_accs.append(correct / total)\n",
    "    \n",
    "    # Validation\n",
    "    model.eval()\n",
    "    val_loss, val_correct, val_total = 0.0, 0, 0\n",
    "    with torch.no_grad():\n",
    "        for inputs, labels in val_loader:\n",
    "            inputs, labels = inputs.to(device), labels.float().to(device)\n",
    "            outputs = model(inputs).squeeze()\n",
    "            loss = criterion(outputs, labels)\n",
    "            val_loss += loss.item() * inputs.size(0)\n",
    "            preds = (torch.sigmoid(outputs) > 0.5).float()\n",
    "            val_correct += (preds == labels).sum().item()\n",
    "            val_total += labels.size(0)\n",
    "            \n",
    "    val_losses.append(val_loss / val_total)\n",
    "    val_accs.append(val_correct / val_total)\n",
    "    print(f\"Epoch {epoch+1}/{epochs} | Train Acc: {train_accs[-1]:.4f} | Val Acc: {val_accs[-1]:.4f}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "plt.figure(figsize=(12, 4))\n",
    "plt.subplot(1, 2, 1)\n",
    "plt.plot(train_accs, label='Train Accuracy')\n",
    "plt.plot(val_accs, label='Validation Accuracy')\n",
    "plt.legend()\n",
    "plt.title('Model Accuracy')\n",
    "\n",
    "plt.subplot(1, 2, 2)\n",
    "plt.plot(train_losses, label='Train Loss')\n",
    "plt.plot(val_losses, label='Validation Loss')\n",
    "plt.legend()\n",
    "plt.title('Model Loss')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay\n",
    "\n",
    "print(\"Memuat Data Test...\")\n",
    "X_test, y_true_numeric = load_data(\"dataset/test\")\n",
    "\n",
    "print(\"\\nEvaluasi Data Test...\")\n",
    "model.eval()\n",
    "with torch.no_grad():\n",
    "    test_inputs = torch.tensor(X_test).to(device)\n",
    "    test_outputs = model(test_inputs).squeeze()\n",
    "    if test_outputs.dim() == 0:  # Jika hanya 1 data\n",
    "        test_outputs = test_outputs.unsqueeze(0)\n",
    "    probs = torch.sigmoid(test_outputs)\n",
    "    y_pred_numeric = (probs > 0.5).cpu().numpy().astype(int)\n",
    "\n",
    "y_true = [\"Helm\" if y == 0 else \"Kacamata\" for y in y_true_numeric]\n",
    "y_pred = [\"Helm\" if y == 0 else \"Kacamata\" for y in y_pred_numeric]\n",
    "\n",
    "labels = [\"Helm\", \"Kacamata\"]\n",
    "cm = confusion_matrix(y_true, y_pred, labels=labels)\n",
    "disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)\n",
    "disp.plot(cmap=\"Blues\")\n",
    "plt.title(\"Confusion Matrix - PyTorch CNN\")\n",
    "plt.show()\n",
    "\n",
    "print(\"\\n--- CLASSIFICATION REPORT ---\")\n",
    "print(classification_report(y_true, y_pred, labels=labels, zero_division=0))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def classify_demo_pytorch(image_path, cnn_model):\n",
    "    img = cv2.imread(image_path)\n",
    "    if img is None:\n",
    "        return \"Error\"\n",
    "    \n",
    "    img_resized = cv2.resize(img, IMG_SIZE)\n",
    "    img_rgb = cv2.cvtColor(img_resized, cv2.COLOR_BGR2RGB)\n",
    "    \n",
    "    img_tensor = np.transpose(img_rgb, (2, 0, 1)).astype(np.float32) / 255.0\n",
    "    input_tensor = torch.tensor(img_tensor).unsqueeze(0).to(device)\n",
    "    \n",
    "    cnn_model.eval()\n",
    "    with torch.no_grad():\n",
    "        output = cnn_model(input_tensor).squeeze()\n",
    "        prob = torch.sigmoid(output).item()\n",
    "        \n",
    "    pred_id = 1 if prob > 0.5 else 0\n",
    "    predicted_label = \"Kacamata\" if pred_id == 1 else \"Helm\"\n",
    "    \n",
    "    plt.figure(figsize=(4, 4))\n",
    "    plt.imshow(img_rgb)\n",
    "    plt.title(f\"CNN: {predicted_label} (Prob Kacamata: {prob:.2f})\")\n",
    "    plt.axis(\"off\")\n",
    "    plt.show()\n",
    "    \n",
    "    return predicted_label\n",
    "\n",
    "print(\"=== DEMO KLASIFIKASI CNN ===\")\n",
    "helm_samples = glob.glob(\"dataset/test/helm/*.*\")\n",
    "if helm_samples:\n",
    "    classify_demo_pytorch(helm_samples[0], model)\n",
    "\n",
    "kaca_samples = glob.glob(\"dataset/test/kacamata/*.*\")\n",
    "if kaca_samples:\n",
    "    classify_demo_pytorch(kaca_samples[0], model)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("new_cnn_pytorch.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook new_cnn_pytorch.ipynb berhasil dibuat!")
