import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Klasifikasi Kacamata dan Helm Menggunakan GLCM + HOG + LBP + KNN\n",
    "Notebook ini mengimplementasikan klasifikasi menggunakan kombinasi ekstraksi fitur **GLCM** (tekstur), **HOG** (bentuk), dan **LBP** (pola lokal), kemudian diklasifikasikan menggunakan **KNN** dengan nilai K optimal."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import os\n",
    "import glob\n",
    "import matplotlib.pyplot as plt\n",
    "from tqdm.notebook import tqdm\n",
    "from skimage.feature import graycomatrix, graycoprops, hog, local_binary_pattern\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay\n",
    "\n",
    "IMG_SIZE = (128, 128)\n",
    "CLASSES  = ['helm', 'kacamata']\n",
    "\n",
    "def extract_features(image_path):\n",
    "    \"\"\"Mengekstrak fitur GLCM + HOG + LBP dari gambar.\"\"\"\n",
    "    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)\n",
    "    if img is None:\n",
    "        return None\n",
    "\n",
    "    # 1. Resize\n",
    "    img_resized = cv2.resize(img, IMG_SIZE)\n",
    "\n",
    "    # 2. CLAHE: Contrast Limited Adaptive Histogram Equalization\n",
    "    #    Meningkatkan kontras lokal agar fitur lebih diskriminatif\n",
    "    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))\n",
    "    img_enhanced = clahe.apply(img_resized)\n",
    "\n",
    "    # 3. GLCM - Fitur Tekstur\n",
    "    distances = [1, 3]\n",
    "    angles    = [0, np.pi/4, np.pi/2, 3*np.pi/4]\n",
    "    glcm = graycomatrix(img_enhanced, distances=distances, angles=angles,\n",
    "                        levels=256, symmetric=True, normed=True)\n",
    "    glcm_features = np.hstack([\n",
    "        graycoprops(glcm, 'contrast').flatten(),\n",
    "        graycoprops(glcm, 'correlation').flatten(),\n",
    "        graycoprops(glcm, 'energy').flatten(),\n",
    "        graycoprops(glcm, 'homogeneity').flatten(),\n",
    "        graycoprops(glcm, 'ASM').flatten(),\n",
    "        graycoprops(glcm, 'dissimilarity').flatten(),\n",
    "    ])  # 48 dimensi\n",
    "\n",
    "    # 4. HOG - Fitur Bentuk/Gradien\n",
    "    hog_features = hog(\n",
    "        img_enhanced, orientations=8,\n",
    "        pixels_per_cell=(16, 16), cells_per_block=(2, 2),\n",
    "        visualize=False\n",
    "    )  # 1568 dimensi\n",
    "\n",
    "    # 5. LBP - Local Binary Pattern (Pola Tekstur Lokal)\n",
    "    #    Sangat efektif membedakan pola permukaan kacamata vs helm\n",
    "    radius   = 3\n",
    "    n_points = 8 * radius\n",
    "    lbp = local_binary_pattern(img_enhanced, n_points, radius, method='uniform')\n",
    "    lbp_hist, _ = np.histogram(lbp.ravel(), bins=n_points + 2,\n",
    "                                range=(0, n_points + 2), density=True)\n",
    "    # 26 dimensi\n",
    "\n",
    "    return np.hstack([glcm_features, hog_features, lbp_hist])\n",
    "\n",
    "def load_dataset(base_dir):\n",
    "    features_list, labels_list = [], []\n",
    "    for class_idx, class_name in enumerate(CLASSES):\n",
    "        class_dir = os.path.join(base_dir, class_name)\n",
    "        if not os.path.exists(class_dir):\n",
    "            print(f'  Direktori tidak ditemukan: {class_dir}')\n",
    "            continue\n",
    "        files = glob.glob(os.path.join(class_dir, '*.*'))\n",
    "        print(f\"  Kelas '{class_name}': {len(files)} gambar\")\n",
    "        for img_path in tqdm(files, desc=f'Ekstraksi {class_name}'):\n",
    "            feat = extract_features(img_path)\n",
    "            if feat is not None:\n",
    "                features_list.append(feat)\n",
    "                labels_list.append(class_idx)\n",
    "    return np.array(features_list), np.array(labels_list)\n",
    "\n",
    "print('Memuat dataset training (GLCM + HOG + LBP)...')\n",
    "X_raw, y_raw = load_dataset('dataset/train')\n",
    "n_helm      = int(np.sum(y_raw == 0))\n",
    "n_kacamata  = int(np.sum(y_raw == 1))\n",
    "print(f'\\nSelesai! Total: {X_raw.shape[0]} sampel | helm={n_helm} | kacamata={n_kacamata}')\n",
    "print(f'Dimensi fitur per gambar: {X_raw.shape[1]} (GLCM=48, HOG=1568, LBP=26)')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Mencari Nilai K Optimal\n",
    "Gunakan `weights='distance'` agar tetangga yang lebih dekat mendapat bobot lebih besar — ini mengurangi pengaruh kelas mayor (helm) yang jumlahnya lebih banyak."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_tr, X_val, y_tr, y_val = train_test_split(\n",
    "    X_raw, y_raw, test_size=0.2, random_state=42, stratify=y_raw\n",
    ")\n",
    "scaler_val   = StandardScaler()\n",
    "X_tr_scaled  = scaler_val.fit_transform(X_tr)\n",
    "X_val_scaled = scaler_val.transform(X_val)\n",
    "\n",
    "print(f'Data Training: {X_tr_scaled.shape[0]} | Data Validasi: {X_val_scaled.shape[0]}')\n",
    "print('\\nMencari nilai K optimal (dengan distance-weighting)...')\n",
    "\n",
    "k_values       = list(range(1, 16, 2))\n",
    "val_accuracies = []\n",
    "\n",
    "for k in k_values:\n",
    "    # weights='distance': tetangga lebih dekat = bobot lebih besar\n",
    "    knn = KNeighborsClassifier(n_neighbors=k, weights='distance', metric='euclidean')\n",
    "    knn.fit(X_tr_scaled, y_tr)\n",
    "    acc = accuracy_score(y_val, knn.predict(X_val_scaled))\n",
    "    val_accuracies.append(acc)\n",
    "    print(f'  k = {k:2d}  ->  Akurasi Validasi: {acc*100:.2f}%')\n",
    "\n",
    "# Visualisasi\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(k_values, val_accuracies, marker='o', linestyle='-',\n",
    "         color='#1e88e5', linewidth=2.5, markersize=8)\n",
    "plt.title('Nilai K vs Akurasi Validasi (GLCM + HOG + LBP, distance-weighted)',\n",
    "          fontsize=13, fontweight='bold', pad=15)\n",
    "plt.xlabel('Nilai K', fontsize=12)\n",
    "plt.ylabel('Akurasi Validasi', fontsize=12)\n",
    "plt.grid(True, linestyle='--', alpha=0.5)\n",
    "plt.xticks(k_values)\n",
    "for i, acc in enumerate(val_accuracies):\n",
    "    plt.annotate(f'{acc:.4f}', (k_values[i], acc),\n",
    "                 textcoords='offset points', xytext=(0, 10),\n",
    "                 ha='center', fontsize=9, fontweight='bold')\n",
    "plt.ylim(min(val_accuracies) - 0.05, max(val_accuracies) + 0.05)\n",
    "plt.tight_layout()\n",
    "plt.show()\n",
    "\n",
    "best_k = k_values[int(np.argmax(val_accuracies))]\n",
    "print(f'\\nK optimal: {best_k} (Akurasi Validasi: {max(val_accuracies)*100:.2f}%)')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Pelatihan Model Final\n",
    "Latih pada **seluruh data training** dengan K terbaik dan `weights='distance'`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "scaler_final  = StandardScaler()\n",
    "X_train_final = scaler_final.fit_transform(X_raw)\n",
    "\n",
    "knn_final = KNeighborsClassifier(n_neighbors=best_k,\n",
    "                                  weights='distance',\n",
    "                                  metric='euclidean')\n",
    "knn_final.fit(X_train_final, y_raw)\n",
    "print(f'Model KNN Final (k={best_k}, weights=distance, fitur=GLCM+HOG+LBP) siap!')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Demo Klasifikasi: Visualisasi Tahapan Preprocessing\n",
    "Menampilkan setiap tahapan preprocessing pada contoh gambar."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "def classify_and_visualize(image_path, model, scaler_model):\n",
    "    img_bgr = cv2.imread(image_path)\n",
    "    if img_bgr is None:\n",
    "        print(f'Gambar tidak ditemukan: {image_path}')\n",
    "        return\n",
    "\n",
    "    h_orig, w_orig = img_bgr.shape[:2]\n",
    "    img_gray_orig  = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2GRAY)\n",
    "    img_resized    = cv2.resize(img_gray_orig, IMG_SIZE)\n",
    "    clahe_obj      = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))\n",
    "    img_enhanced   = clahe_obj.apply(img_resized)\n",
    "\n",
    "    _, hog_image = hog(\n",
    "        img_enhanced, orientations=8, pixels_per_cell=(16, 16),\n",
    "        cells_per_block=(2, 2), visualize=True\n",
    "    )\n",
    "\n",
    "    feat      = extract_features(image_path)\n",
    "    feat_sc   = scaler_model.transform([feat])\n",
    "    pred_id   = model.predict(feat_sc)[0]\n",
    "    proba     = model.predict_proba(feat_sc)[0]\n",
    "    label     = CLASSES[pred_id]\n",
    "    confidence = proba[pred_id] * 100\n",
    "\n",
    "    fig, axes = plt.subplots(1, 4, figsize=(18, 4))\n",
    "    axes[0].imshow(cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB))\n",
    "    axes[0].set_title(f'1. Gambar Asli\\n({w_orig}x{h_orig})')\n",
    "    axes[1].imshow(cv2.cvtColor(cv2.resize(img_bgr, IMG_SIZE), cv2.COLOR_BGR2RGB))\n",
    "    axes[1].set_title(f'2. Resize\\n({IMG_SIZE[0]}x{IMG_SIZE[1]})')\n",
    "    axes[2].imshow(img_enhanced, cmap='gray')\n",
    "    axes[2].set_title(f'3. Grayscale + CLAHE\\n({IMG_SIZE[0]}x{IMG_SIZE[1]})')\n",
    "    axes[3].imshow(hog_image, cmap='gray')\n",
    "    color_title = 'green' if pred_id == 1 else 'red'\n",
    "    axes[3].set_title(f'4. HOG Features\\nKNN: {label.upper()} ({confidence:.1f}%)',\n",
    "                      color=color_title, fontweight='bold')\n",
    "    for ax in axes:\n",
    "        ax.axis('off')\n",
    "    plt.tight_layout()\n",
    "    plt.show()\n",
    "\n",
    "print('=== DEMO: Contoh dari Dataset Test ===')\n",
    "helm_samples = glob.glob('dataset/test/helm/*.*')\n",
    "if helm_samples:\n",
    "    print('Contoh Helm:')\n",
    "    classify_and_visualize(helm_samples[0], knn_final, scaler_final)\n",
    "\n",
    "kaca_samples = glob.glob('dataset/test/kacamata/*.*')\n",
    "if kaca_samples:\n",
    "    print('Contoh Kacamata:')\n",
    "    classify_and_visualize(kaca_samples[0], knn_final, scaler_final)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Evaluasi Model pada Dataset Test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "print('Memuat dataset test...')\n",
    "X_test_raw, y_test = load_dataset('dataset/test')\n",
    "print(f'Selesai! Jumlah sampel test: {X_test_raw.shape[0]}')\n",
    "\n",
    "X_test_scaled = scaler_final.transform(X_test_raw)\n",
    "y_pred        = knn_final.predict(X_test_scaled)\n",
    "\n",
    "test_accuracy = accuracy_score(y_test, y_pred)\n",
    "labels_name   = ['Helm', 'Kacamata']\n",
    "print(f'\\nAkurasi KNN + GLCM + HOG + LBP pada Test Set: {test_accuracy * 100:.2f}%')\n",
    "print('\\n--- CLASSIFICATION REPORT ---')\n",
    "print(classification_report(y_test, y_pred, target_names=labels_name, zero_division=0))\n",
    "\n",
    "cm   = confusion_matrix(y_test, y_pred)\n",
    "disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels_name)\n",
    "fig, ax = plt.subplots(figsize=(6, 6))\n",
    "disp.plot(cmap='Blues', ax=ax, values_format='d')\n",
    "plt.title('Confusion Matrix - KNN + GLCM + HOG + LBP', fontsize=12, fontweight='bold')\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🧪 Pengujian 10 Gambar (5 Helm, 5 Kacamata) dari Test Set\n",
    "Mengambil masing-masing 5 gambar helm dan 5 kacamata dari dataset test yang digunakan pada confusion matrix, lalu menampilkan hasil prediksinya."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import glob\n",
    "import os\n",
    "import random\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "print('=== Pengujian 10 Gambar Acak (5 Helm, 5 Kacamata) dari Test Set ===')\n",
    "\n",
    "# Mengambil 5 gambar helm dan 5 gambar kacamata secara acak\n",
    "helm_all = glob.glob('dataset/test/helm/*.*')\n",
    "kacamata_all = glob.glob('dataset/test/kacamata/*.*')\n",
    "\n",
    "helm_samples = random.sample(helm_all, min(5, len(helm_all)))\n",
    "kacamata_samples = random.sample(kacamata_all, min(5, len(kacamata_all)))\n",
    "\n",
    "test_images = helm_samples + kacamata_samples\n",
    "\n",
    "fig, axes = plt.subplots(2, 5, figsize=(20, 8))\n",
    "axes = axes.flatten()\n",
    "\n",
    "for i, img_path in enumerate(test_images):\n",
    "    if not os.path.exists(img_path):\n",
    "        continue\n",
    "        \n",
    "    features = extract_features(img_path)\n",
    "    if features is None:\n",
    "        continue\n",
    "        \n",
    "    features_scaled = scaler_final.transform([features])\n",
    "    prediction      = knn_final.predict(features_scaled)[0]\n",
    "    probabilities   = knn_final.predict_proba(features_scaled)[0]\n",
    "    predicted_class = CLASSES[prediction]\n",
    "    confidence      = probabilities[prediction] * 100\n",
    "    \n",
    "    img_bgr = cv2.imread(img_path)\n",
    "    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)\n",
    "    \n",
    "    true_label = 'helm' if 'helm' in img_path.lower() else 'kacamata'\n",
    "    color = '#2e7d32' if predicted_class.lower() == true_label else '#c62828'\n",
    "    \n",
    "    axes[i].imshow(img_rgb)\n",
    "    axes[i].set_title(\n",
    "        f'Asli: {true_label.upper()}\\nPrediksi: {predicted_class.upper()}\\nConf: {confidence:.1f}%',\n",
    "        fontsize=11, fontweight='bold', color=color\n",
    "    )\n",
    "    axes[i].axis('off')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {"name": "ipython", "version": 3},
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbformat": 4,
   "nbformat_minor": 4,
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("new_knn.ipynb", "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=1)
print("Notebook new_knn.ipynb dengan GLCM+HOG+LBP berhasil dibuat!")
